# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e92ab0fa55855482a3ecddb455f1a882a95187ee7298689c4f1d739b9b25f5a39b2506a1dc244cba93c35dc02bda0ada21843c9e07e76cdba17100e2656e915

test:
  secret_key_base: da86ef1cb3ec8cd84709e99282ae524f9e12be442374430109f49f9e4c6a162d3baa6f43a57713b887097a772a1acc702b29e4ed4d41e9c1921663cffe7c4858

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
